---

ca_domain: "johnson.int"

ca_static_configs:
  admin01:
    ca_service_route: "admin.{{ ca_domain }}"
    ca_domain: "{{ ca_domain }}"
    ca_common_name: "admin01.{{ ca_domain }}"
    ca_signer_common_name: "ca.{{ ca_domain }}"
    ca_parent_signer_common_name: "ca-root"
  admin02:
    ca_service_route: "admin.{{ ca_domain }}"
    ca_domain: "{{ ca_domain }}"
    ca_common_name: "admin02.{{ ca_domain }}"
    ca_signer_common_name: "ca.{{ ca_domain }}"
    ca_parent_signer_common_name: "ca-root"
  web01:
    ca_service_route: "web.{{ ca_domain }}"
    ca_domain: "{{ ca_domain }}"
    ca_common_name: "web01.{{ ca_domain }}"
    ca_signer_common_name: "ca.{{ ca_domain }}"
    ca_parent_signer_common_name: "ca-root"
  web02:
    ca_service_route: "web.{{ ca_domain }}"
    ca_domain: "{{ ca_domain }}"
    ca_common_name: "web02.{{ ca_domain }}"
    ca_signer_common_name: "ca.{{ ca_domain }}"
    ca_parent_signer_common_name: "ca-root"
  web03:
    ca_service_route: "web.{{ ca_domain }}"
    ca_domain: "{{ ca_domain }}"
    ca_common_name: "web03.{{ ca_domain }}"
    ca_signer_common_name: "ca.{{ ca_domain }}"
    ca_parent_signer_common_name: "ca-root"
  db01:
    ca_service_route: "db.{{ ca_domain }}"
    ca_domain: "{{ ca_domain }}"
    ca_common_name: "db01.{{ ca_domain }}"
    ca_signer_common_name: "ca.{{ ca_domain }}"
    ca_parent_signer_common_name: "ca-root"
  media01:
    ca_service_route: "media.{{ ca_domain }}"
    ca_domain: "{{ ca_domain }}"
    ca_common_name: "media01.{{ ca_domain }}"
    ca_signer_common_name: "ca.{{ ca_domain }}"
    ca_parent_signer_common_name: "ca-root"
  localhost:
    ca_service_route: "admin.{{ ca_domain }}"
    ca_domain: "{{ ca_domain }}"
    ca_common_name: "localhost.{{ ca_domain }}"
    ca_signer_common_name: "ca.{{ ca_domain }}"
    ca_parent_signer_common_name: "ca-root"


ca_domains_dynamic: "{{ groups['ca_domain'] | map('extract', hostvars, ['internal_domain']) | select('defined') | unique }}"
ca_routes_dynamic: "{{ groups['ca_domain'] | map('extract', hostvars, ['ca_service_route']) | select('defined') | unique | d([]) }}"

ca_intermediate_certs_list_dynamic: |
  [
    {% for domain in ca_domains_dynamic %}
    {% if domain not in ca_intermediate_certs_config %}
    {
      'commonName': "ca.{{ domain }}",
      'domainName': "{{ domain }}",
      'signerName': "{{ 'ca.' + ('.').join(ca_domain_name.split('.')[1::]) if ca_domain_name.split('.')|count>2 else ca_root_cn }}"
    },
    {% endif %}
    {% endfor %}
  ]

#ca_intermediate_certs_list: "{{ ca_intermediate_certs_list_static + ca_intermediate_certs_list_dynamic }}"
ca_intermediate_certs_list: "{{ ca_intermediate_certs_config.values() | d({}) | list + ca_intermediate_certs_list_dynamic }}"

ca_service_routes_list: |
  [
    {% for domain in ca_routes_dynamic %}
    {
      'route': "{{ domain }}",
      'signerName': "ca.{{ domain }}"
    },
    {% endfor %}
  ]

