---

app_http_port__app_c: 11080
app_https_port__app_c: 11443

app_config_dirs__app_c:
  - { path: "{{ app_base_dir }}/app-service-c" }

app_firewalld_ports__app_c:
  - "{{ app_http_port__app_c }}/tcp"
  - "{{ app_https_port__app_c }}/tcp"
#  - "11080/tcp"
#  - "11443/tcp"
