---

app_http_port__app_a: 3000
app_ssh_port__app_a: 2222

app_config_dirs__app_a:
  - { path: "{{ app_base_dir }}/app-service-a" }

app_firewalld_ports__app_a:
  - "{{ app_http_port__app_a }}/tcp"
  - "{{ app_ssh_port__app_a }}/tcp"
