---

app_http_port__app_b: 10080
app_https_port__app_b: 10443

app_config_dirs__app_b:
  - { path: "{{ app_base_dir }}/app-service-b" }

app_firewalld_ports__app_b:
  - "{{ app_http_port__app_b }}/tcp"
  - "{{ app_https_port__app_b }}/tcp"
