---


- name: Apply role
  gather_facts: no
  hosts: localhost
  vars:
    app_configs:
      - name: config1
        src: somewhere/there/is/something
        dest: somewhereelse/there/is/somethingelse
      - name: config2
        src: somewhere/there/is/something
        dest: somewhereelse/there/is/somethingelse
      - name: config3
        src: foo/bar/rab/oof
        dest: blah/bleh/meeh/mah
  tasks:
    - name: deploy app
      include_role:
        name: app-config
        tasks_from: deploy-configs.yml
    #    public: true
      loop: "{{ app_configs }}"
      loop_control:
        loop_var: app_config
