---

## https://docs.ansible.com/ansible/latest/collections/ansible/builtin/varnames_lookup.html
#- name: Get variables that start with ca_
#  debug: msg="{{ lookup('varnames', '^ca_.+') | to_nice_yaml }}"

#- name: List variables that start with ca_
#  debug:
#    msg: "{{ item.0 }}: {{ item.1 }}"
#  with_nested:
#    - "{{ groups['ca_domain_service_route'] }}"
#    - "{{ lookup('varnames', '^ca_.+') }}"
#  loop_control:
#    label: "{{ item.0 }} - {{ item.1 }}"

- name: List variables that start with ca_
  debug:
    msg: "hostvars[{{item}}].ca_service_route={{hostvars[item].ca_service_route}}"
  loop: "{{ groups['ca_domain_service_route'] }}"

- name: "Check that service routes are correctly defined"
  assert:
    that:
      - hostvars[item].ca_service_route == ca_static_configs[item].ca_service_route
      - hostvars[item].ca_common_name == ca_static_configs[item].ca_common_name
      - hostvars[item].ca_signer_common_name == ca_static_configs[item].ca_signer_common_name
      - hostvars[item].ca_parent_signer_common_name == ca_static_configs[item].ca_parent_signer_common_name
  loop: "{{ groups['ca_domain_service_route'] }}"
