---

## https://docs.ansible.com/ansible/latest/collections/ansible/builtin/varnames_lookup.html
- name: List variables that start with qz_
  debug: msg="{{ lookup('varnames', '^ca_.+')}}"

- name: "Check that service routes are correctly defined"
  assert:
    that:
      - hostvars['localhost'].ca_service_route == ca_static_configs['localhost'].ca_service_route
  loop: "{{ groups['ca_domain_service_route'] }}"
