---

- name: Set the app services vars
  include_vars:
    file: "app-services/{{ item }}.yml"
  with_items: "{{ app_services }}"

## used approach detailed here:
##   https://stackoverflow.com/questions/35554415/in-ansible-how-to-combine-variables-from-separate-files-into-one-array
##    response: https://stackoverflow.com/a/63268576
##   https://serverfault.com/questions/685673/appending-to-lists-or-adding-keys-to-dictionaries-in-ansible
##   https://docs.ansible.com/ansible/latest/user_guide/complex_data_manipulation.html

#- name: Lookup varnames to combine
#  set_fact:
#    app_config_dir_varnames: "{{ q('varnames', '^app_config_dirs__') }}"
#
#- name: Combine varname configs into one dict
#  set_fact:
#    app_config_dirs: "{{ dict(app_config_dir_varnames | zip(q('vars', *app_config_dir_varnames))) }}"

- name: Combine varname configs into one dict
  set_fact:
    app_config_dirs: "{{ app_config_dirs|d({}) | combine({ item: lookup('vars', q('varnames','^app_config_dirs__'+item.replace('-','_')+'$')| first)|d({}) }) }}"
  loop: "{{ app_services }}"

- name: "print app_configs - after dereference"
  debug:
    var: app_config_dirs

